name: syai_autobiz
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pyyaml==6.0
  - requests==2.27.1
  - webdriver-manager==3.8.5
  - chromedriver-autoinstaller==0.4.0
  - selenium==3.141.0
  - pyperclip 1.8.2

# conda env create --file environment.yaml